// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentService.Data;

#nullable disable

namespace PaymentService.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentService.Entities.InventoryHold", b =>
                {
                    b.Property<int>("MaGiuCho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiuCho"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("HetHanLuc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("MaBienSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("MaChiTietDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaGiuCho");

                    b.HasIndex("MaDonHang");

                    b.ToTable("TONKHO_GIUCHO", (string)null);
                });

            modelBuilder.Entity("PaymentService.Entities.Order", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("LoaiDonHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LyDoHuyDon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaDonHangKinhDoanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("NgayHuyDon")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("NgayThanhToanThanhCong")
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal>("SoTienConLai")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienDatCoc")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThanhToan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDonHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaDonHang");

                    b.ToTable("DONHANG", (string)null);
                });

            modelBuilder.Entity("PaymentService.Entities.Payment", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<DateTime?>("DaThanhToanLuc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("LoaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("MaNganHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaThanhToanKinhDoanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayHuy")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("NoiDungChuyenKhoan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ResponseRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaGiaoDich")
                        .IsUnique()
                        .HasFilter("[MaGiaoDich] IS NOT NULL");

                    b.HasIndex("MaThanhToanKinhDoanh")
                        .IsUnique();

                    b.HasIndex("MaDonHang", "TrangThai", "NgayTao");

                    b.ToTable("THANHTOAN", null, t =>
                        {
                            t.HasCheckConstraint("CK_THANHTOAN_LoaiThanhToan", "[LoaiThanhToan] IN ('Full','Deposit','Remaining')");

                            t.HasCheckConstraint("CK_THANHTOAN_PhuongThuc", "[PhuongThuc] IN ('COD','BankTransfer','Card','Momo','VNPay')");

                            t.HasCheckConstraint("CK_THANHTOAN_SoTien", "[SoTien] > 0");

                            t.HasCheckConstraint("CK_THANHTOAN_TrangThai", "[TrangThai] IN ('Pending','Paid','Failed','Cancelled')");
                        });
                });

            modelBuilder.Entity("PaymentService.Entities.Product", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("MaSanPham");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("PaymentService.Entities.ProductVariant", b =>
                {
                    b.Property<int>("MaBienSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBienSanPham"));

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaBienSanPham");

                    b.ToTable("BIENSANPHAM", (string)null);
                });

            modelBuilder.Entity("PaymentService.Entities.User", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NGUOIDUNG", (string)null);
                });

            modelBuilder.Entity("PaymentService.Entities.InventoryHold", b =>
                {
                    b.HasOne("PaymentService.Entities.Order", "Order")
                        .WithMany("InventoryHolds")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PaymentService.Entities.Payment", b =>
                {
                    b.HasOne("PaymentService.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PaymentService.Entities.Order", b =>
                {
                    b.Navigation("InventoryHolds");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
