SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
GO

IF OBJECT_ID(N'dbo.BANGGIA_VANCHUYEN', N'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.BANGGIA_VANCHUYEN;
END;
GO

IF OBJECT_ID(N'dbo.DONVI_VANCHUYEN', N'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.DONVI_VANCHUYEN;
END;
GO
